import React from "react";
const Physics = [
   {
    key : 1,
    id : 1,
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",
    question : "A block of mass slides along a floor while a force of magnitude is applied to it at an angle as shown in figure. The coefficient of kinetic friction is . Then, the block\'s acceleration \'a\' is given by : (g is acceleration due to gravity)",
    img : "p1.png",
    option1 : "−F/m cos θ − μK (g − F/msin θ)",
    option2 : "F/mcos θ − μK (g − F/msin θ)",
    option3 : "F/mcos θ − μK (g + F/msin θ)",
    option4 : "F/mcos θ + μK (g − F/msin θ)",
    style : "white",
    inputtag : [false,false,false,false]
   },{
    key : 2,
    id : 2,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",
    question : "What are the laws of motion?",
    option1 : "Every Object tends to be in same state of position unill an external force is applied on it",
    option2 : "for a given force ,  the acceleration gained inversely proportional to the mass of that body",
    option3 : "Every Action causes equal and opposite reaction",
    option4 : "All of the above",
    style : "white",
    inputtag : [false,false,false,false]
   },{
    key : 3,
    id : 3,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",
    question : "A value of θ for which (2+3i sinθ)/(1-2i sinθ) is purely imaginary is :",
    option1 : "sin-1(1/√3)",
    option2 : "π/3",
    option3 : "sin-1(√3/4)",
    option4 : "π/3",
    style : "white",
    inputtag : [false,false,false,false]
   },{
    key : 4,
    id : 4,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

    question : "A man is walking towards a vertical pillar in a straight path, at a uniform speed. At a certain point A on the path, he observes that the angle of elevation of the top of the pillar is 30°. After walking for 10 minutes from A in the same direction, at a point B, he observes that the angle of elevation of the top of the pillar is 60°. Then the time taken (in minutes) by him, form B to reach the pillar, is:",
    option1 : "5",
    option2 : "6",
    option3 : "10",
    option4 : "15",
    style : "white",
    inputtag : [false,false,false,false]
   },
   { key : 5,
    id : 5,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

    question : "If all the words (with or without meaning) having five letters, formed using the letters of the word SMALL and arranged as in a dictionary; then the position of the word SMALL is :",
    option1 : "58th",
    option2 : "46th",
    option3 : "59th",
    option4 : "62th",
    style : "white",
    inputtag : [false,false,false,false]},
   { key : 6,
    id : 6,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

    question : "Half-lives of two radioactive elements A and B are 20 minutes and 40 minutes, respectively. Initially, the samples have equal number of nuclei. After 80 minutes , the ratio of decayed numbers of A and B nuclei will be :- ",
    option1 : "5:4",
    option2 : "1:16",
    option3 : "4:1",
    option4 : "1:4",
    style : "white",
    inputtag : [false,false,false,false]},
   { key : 7,
    id : 7,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

    question: "A person trying to lose weight by burning fat lifts a mass of 10 kg upto a height of 1 m 1000 times. Assume that the potential energy lost each time he lowers the mass is dissipated. How much fat will he use up considering the work done only when the weight is lifted up? Fat supplies 3.8 × 107 J of energy per kg which is converted to mechanical energy with a 20% efficiency rate. Take g = 9.8 ms–2 :-",
    option1 : "12.89 × 10–3 kg",
    option2 : "2.45 × 10–3 kg",
    option3 : "6.45 × 10–3 kg",
    option4 : "9.89 × 10–3 kg",style : "white",
    inputtag : [false,false,false,false]},
   { key : 8,
    id : 8,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

    question : "A pipe open at both ends has a fundamental frequency f in air. The pipe is dipped vertically in water so that half of it is in water. The fundamental frequency of the air column is now :-", 
    option1 : "f",
    option2 : "f/2",
    option3 : "3f/4",
    option4 : "2f",style : "white", inputtag : [false,false,false,false]}
   ,{ key : 9,
    id : 9,
    img : "/",
    instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

    question : "Galvanization is applying a coating of :-",
    option1 : "Zn",
    option2 : "Pb",
    option3 : "Cr",
    option4 : "Cu",style : "white", inputtag : [false,false,false,false]},
    { key : 10,
        id : 10,
        img : "/",
        instructions : "There are 3 sections and 10 questions in this exam. You must click one  question to answer it. Read the questions carefully and confine your responses to an analysis of the questions as written. Do not assume any facts not set forth in the questions. You have 3 hours to complete the exam. You may allocate your time as you wish. I recommend that you spend some time organizing your thoughts before you begin to write and that you reserve some time to go over your responses after you have completed the exam. Good luck. ",

        question : "The heats of combustion of carbon and carbon monoxide are -393.5 and -285.5 kJ mol-1 respectively. The heat of formation (in kJ) of carbon monoxide per mole is:",
        option1 : "-110.5",
        option2 : "110.5",
        option3 : "676.5",
        option4 : "-676.5",style : "white", inputtag : [false,false,false,false]}
];
export default Physics ;